config_type: bot
code: base_config
description: Base config fot the bot
logger:
  console: debug
  file: debug
  # telegram

telegram:
  chat_id: ''
  bot_token: ''



strategies:
  path: 'strategies'

exchanges:
  path: null

  # TODO to args

  #exchanges:
  #  - binance
  #  #- kucoin

  #market_types:
  #  - stock
  #  - futures

#credentials:
#  stock:
#    binance:
#      api_key: ''
#      secret_key: ''
#
#  futures:
#    binance:
#      api_key: ''
#      secret_key: ''